apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-helm-chart.backendName" . }}
  labels:
    app: {{ include "todo-helm-chart.name" . }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-helm-chart.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "todo-helm-chart.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
            - name: DB_HOST
              value: "{{ .Values.backend.env.DB_HOST }}"
            - name: DB_USER
              value: "{{ .Values.backend.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.backend.env.DB_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.backend.env.DB_NAME }}"
            - name: DB_PORT
              value: "{{ .Values.backend.env.DB_PORT }}"
