apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-helm-chart.frontendName" . }}
  labels:
    app: {{ include "todo-helm-chart.name" . }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "todo-helm-chart.name" . }}
    component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
